### ISSUE TITLE
Tracking: fix CI failure on smoke test

### ISSUE THREAD

**Issue by sehz** [infinyon/fluvio#107]
Bunch of failures in CI:

* #110 Use Fluvio CLI to install local cluster
*  #111  Make unit test more robust in the Github Action
* Make smoke test more robust when running using Github Action

```
0s
12
##[error]Process completed with exit code 101.
1
Run ./target/debug/flv-test -d --local-driver
6
using local environment driver
7
remove cluster skipped
8
installing cluster
9
>> /home/runner/work/fluvio/fluvio/target/debug/fluvio cluster install --spu 1 --local
10
thread 'main' panicked at 'assertion failed: output.status.success()', tests/runner/src/util/cmd.rs:42:9
11
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by sehz** [comment]
```
Run FLV_CMD=true ./target/debug/flv-test -d --local-driver
6
using local environment driver
7
remove cluster skipped
8
installing cluster
9
>> /home/runner/work/fluvio/fluvio/target/debug/fluvio cluster install --spu 1 --local
10
error: Permission denied (os error 13)
11
creating test topic: <topic1>
12
>> /home/runner/work/fluvio/fluvio/target/debug/fluvio topic create topic1 --replication 1
13
thread 'main' panicked at 'assertion failed: false', tests/runner/src/util/cmd.rs:92:13
14
Exited with status code: 255
15
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
