### ISSUE TITLE
Unstable tests (stream fetch tests) failed in staging but not CI

### ISSUE THREAD

**Issue by nicholastmosher** [infinyon/fluvio#1266]
Unstable tests (stream fetch tests) failed in staging but not CI

![image](https://user-images.githubusercontent.com/4210949/126166049-d22dab31-b3d2-4264-bc3c-716fbcdf559e.png)

```
failures:

---- services::public::stream_fetch::test::test_stream_fetch_sync stdout ----
thread 'services::public::stream_fetch::test::test_stream_fetch_sync' panicked at 'send offset: IoError(Custom { kind: TimedOut, error: "time out in serial: 1005 request: 2" })', src/spu/src/services/public/stream_fetch.rs:588:18
stack backtrace:
   0:     0x5625ee8a0fe0 - std::backtrace_rs::backtrace::libunwind::trace::ha5edb8ba5c6b7a6c
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x5625ee8a0fe0 - std::backtrace_rs::backtrace::trace_unsynchronized::h0de86d320a827db2
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5625ee8a0fe0 - std::sys_common::backtrace::_print_fmt::h97b9ad6f0a1380ff
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x5625ee8a0fe0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h14be7eb08f97fe80
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x5625ee8c794f - core::fmt::write::h2ca8877d3e0e52de
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/fmt/mod.rs:1094:17
   5:     0x5625ee89a1c5 - std::io::Write::write_fmt::h810c53ed5d25925a
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/io/mod.rs:1584:15
   6:     0x5625ee8a35ab - std::sys_common::backtrace::_print::h7f1a4097308f2e0a
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x5625ee8a35ab - std::sys_common::backtrace::print::h1f799fc2ca7f5035
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x5625ee8a35ab - std::panicking::default_hook::{{closure}}::hf38436e8a3ce1071
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:208:50
   9:     0x5625ee8a30b8 - std::panicking::default_hook::he2f8f3fae11ed1dd
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:222:9
  10:     0x5625ee8a3bbd - std::panicking::rust_panic_with_hook::h79a18548bd90c7d4
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:591:17
  11:     0x5625ee8a3757 - std::panicking::begin_panic_handler::{{closure}}::h212a72cc08e25126
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:497:13
  12:     0x5625ee8a147c - std::sys_common::backtrace::__rust_end_short_backtrace::hbd6897dd42bc0fcd
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x5625ee8a36b9 - rust_begin_unwind
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:493:5
  14:     0x5625ed1a9a31 - core::panicking::panic_fmt::h77ecd04e9b1dd84d
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/panicking.rs:92:14
  15:     0x5625ed1a9b23 - core::result::unwrap_failed::hcbdf25d28ce8f0ca
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/result.rs:1355:5
  16:     0x5625ed399f20 - core::result::Result<T,E>::expect::hbb385b350aba2f28
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/result.rs:997:23
  17:     0x5625ed30772c - fluvio_spu::services::public::stream_fetch::test::test_stream_fetch_sync::test_stream_fetch::{{closure}}::hf5f80bc41b0d3471
                               at /home/runner/work/fluvio/fluvio/src/spu/src/services/public/stream_fetch.rs:580:13
  18:     0x5625ed1e2c5b - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h1e23c9fcbe73913f
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/future/mod.rs:80:19
  19:     0x5625ed3045a7 - fluvio_spu::services::public::stream_fetch::test::test_stream_fetch_sync::{{closure}}::hb3ea6fcc9ebebd08
                               at /home/runner/work/fluvio/fluvio/src/spu/src/services/public/stream_fetch.rs:505:5
  20:     0x5625ed1e25db - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h17797b6bde4b1664
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/future/mod.rs:80:19
  21:     0x5625ed47d3a9 - <async_std::task::builder::SupportTaskLocals<F> as core::future::future::Future>::poll::{{closure}}::h2ea4d757bdd343b4
                               at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.9.0/src/task/builder.rs:199:17
  22:     0x5625ed41fd86 - async_std::task::task_locals_wrapper::TaskLocalsWrapper::set_current::{{closure}}::h805586ad85ae576c
                               at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.9.0/src/task/task_locals_wrapper.rs:60:13
  23:     0x5625ed4c369c - std::thread::local::LocalKey<T>::try_with::hc86f8f48eb8429b6
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/thread/local.rs:376:16
  24:     0x5625ed4baead - std::thread::local::LocalKey<T>::with::hcb1b79fc18ad30e7
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/thread/local.rs:352:9
  25:     0x5625ed41e468 - async_std::task::task_locals_wrapper::TaskLocalsWrapper::set_current::h07f07ac9b77978f9
                               at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.9.0/src/task/task_locals_wrapper.rs:55:9
  26:     0x5625ed47ce75 - <async_std::task::builder::SupportTaskLocals<F> as core::future::future::Future>::poll::h4f5fcc6915835a56
                               at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.9.0/src/task/builder.rs:197:13
  27:     0x5625ed233ecb - <futures_lite::future::Or<F1,F2> as core::future::future::Future>::poll::ha933769770135d76
                               at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-lite-1.12.0/src/future.rs:526:33
  28:     0x5625ed55ddd2 - async_executor::Executor::run::{{closure}}::ha5ba222ae4ae14c4
                               at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/async-executor-1.4.1/src/lib.rs:242:9
  29:     0x5625ed1e1ddb - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h0e097062f42079e1
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/future/mod.rs:80:19
  30:     0x5625ed5596c8 - async_executor::LocalExecutor::run::{{closure}}::h819521eca7496aca
                               at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/async-executor-1.4.1/src/lib.rs:447:9
  31:     0x5625ed1ed6bb - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hdce0070f8dd6a425
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/future/mod.rs:80:19
  32:     0x5625ed29c940 - async_io::driver::block_on::hcb33c43615f17d1a
                               at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/async-io-1.6.0/src/driver.rs:142:33
  33:     0x5625ed414315 - async_global_executor::reactor::block_on::{{closure}}::hba1326b5fd0ea23a
                               at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/async-global-executor-2.0.2/src/reactor.rs:3:18
  34:     0x5625ed413da3 - async_global_executor::reactor::block_on::h18026e6c4e09d16a
                               at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/async-global-executor-2.0.2/src/reactor.rs:12:5
  35:     0x5625ed4b8913 - async_global_executor::executor::block_on::{{closure}}::h916de11c0044694e
                               at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/async-global-executor-2.0.2/src/executor.rs:26:36
  36:     0x5625ed4be7ff - std::thread::local::LocalKey<T>::try_with::h4757cd8b083ae0ee
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/thread/local.rs:376:16
  37:     0x5625ed4ba902 - std::thread::local::LocalKey<T>::with::had592fa7df9ef684
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/thread/local.rs:352:9
  38:     0x5625ed4b8656 - async_global_executor::executor::block_on::he3e14f8b270fb5c0
                               at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/async-global-executor-2.0.2/src/executor.rs:26:5
  39:     0x5625ed4a69d6 - async_std::task::builder::Builder::blocking::{{closure}}::{{closure}}::hf04947ccf056e333
                               at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.9.0/src/task/builder.rs:171:25
  40:     0x5625ed420229 - async_std::task::task_locals_wrapper::TaskLocalsWrapper::set_current::{{closure}}::h8f16f4e3fff74c57
                               at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.9.0/src/task/task_locals_wrapper.rs:60:13
  41:     0x5625ed4be57f - std::thread::local::LocalKey<T>::try_with::h470a813742e4b425
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/thread/local.rs:376:16
  42:     0x5625ed4ba430 - std::thread::local::LocalKey<T>::with::h8747696dc3cc8901
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/thread/local.rs:352:9
  43:     0x5625ed41ec97 - async_std::task::task_locals_wrapper::TaskLocalsWrapper::set_current::hc49b3f035939686b
                               at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.9.0/src/task/task_locals_wrapper.rs:55:9
  44:     0x5625ed4a541b - async_std::task::builder::Builder::blocking::{{closure}}::h963900f103a5eac0
                               at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.9.0/src/task/builder.rs:168:17
  45:     0x5625ed4c026f - std::thread::local::LocalKey<T>::try_with::h6c5bf989355d3c87
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/thread/local.rs:376:16
  46:     0x5625ed4bb0c2 - std::thread::local::LocalKey<T>::with::hd37b830ccaa3d4aa
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/thread/local.rs:352:9
  47:     0x5625ed4a2da6 - async_std::task::builder::Builder::blocking::h2d2cb2d5237e1cb1
                               at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.9.0/src/task/builder.rs:161:9
  48:     0x5625ed33293c - async_std::task::block_on::block_on::h468c26c2fa57287e
                               at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.9.0/src/task/block_on.rs:33:5
  49:     0x5625ed3044e1 - fluvio_spu::services::public::stream_fetch::test::test_stream_fetch_sync::h487933b7624b25c2
                               at /home/runner/work/fluvio/fluvio/src/spu/src/services/public/stream_fetch.rs:505:5
  50:     0x5625ed30447a - fluvio_spu::services::public::stream_fetch::test::test_stream_fetch_sync::{{closure}}::h215c370ccc4d1c04
                               at /home/runner/work/fluvio/fluvio/src/spu/src/services/public/stream_fetch.rs:505:5
  51:     0x5625ed2a6b2e - core::ops::function::FnOnce::call_once::he04bb9c1def0a1cd
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/ops/function.rs:227:5
  52:     0x5625ee39af63 - core::ops::function::FnOnce::call_once::h159c05b9c4a4adfd
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/ops/function.rs:227:5
  53:     0x5625ee39af63 - test::__rust_begin_short_backtrace::h2bc63d9f0a571a17
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/test/src/lib.rs:577:5
  54:     0x5625ee399a4f - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h6371fa37d948b8f0
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/alloc/src/boxed.rs:1546:9
  55:     0x5625ee399a4f - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h38d79d5c7ebc8be7
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panic.rs:344:9
  56:     0x5625ee399a4f - std::panicking::try::do_call::h4cd2e2535e9ac92c
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:379:40
  57:     0x5625ee399a4f - std::panicking::try::h5bb7cc83f96fff56
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:343:19
  58:     0x5625ee399a4f - std::panic::catch_unwind::hd3f4bc80671a17b1
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panic.rs:431:14
  59:     0x5625ee399a4f - test::run_test_in_process::h065cff4b82c3b123
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/test/src/lib.rs:600:18
  60:     0x5625ee399a4f - test::run_test::run_test_inner::{{closure}}::h5e25810b3bbf9a81
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/test/src/lib.rs:492:39
  61:     0x5625ee374fbe - test::run_test::run_test_inner::{{closure}}::h334ad608d7480e3e
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/test/src/lib.rs:519:37
  62:     0x5625ee374fbe - std::sys_common::backtrace::__rust_begin_short_backtrace::h978ec215301d6aeb
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:125:18
  63:     0x5625ee378d2f - std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}::h0f65a24521b03e07
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/thread/mod.rs:481:17
  64:     0x5625ee378d2f - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h6284c95f6850b752
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panic.rs:344:9
  65:     0x5625ee378d2f - std::panicking::try::do_call::h9c2002d5a4fe877d
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:379:40
  66:     0x5625ee378d2f - std::panicking::try::he10aa0ee1b65d66f
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:343:19
  67:     0x5625ee378d2f - std::panic::catch_unwind::h2d73c9f6addc723f
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panic.rs:431:14
  68:     0x5625ee378d2f - std::thread::Builder::spawn_unchecked::{{closure}}::h497e00ee57005021
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/thread/mod.rs:480:30
  69:     0x5625ee378d2f - core::ops::function::FnOnce::call_once{{vtable.shim}}::hccce065a7cc059b0
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/ops/function.rs:227:5
  70:     0x5625ee8a9faa - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h75c2ca1daad47228
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/alloc/src/boxed.rs:1546:9
  71:     0x5625ee8a9faa - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hdf9f8afc9d34e311
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/alloc/src/boxed.rs:1546:9
  72:     0x5625ee8a9faa - std::sys::unix::thread::Thread::new::thread_start::hc238bac7748b195d
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys/unix/thread.rs:71:17
  73:     0x7fda8a94e609 - start_thread
  74:     0x7fda8a71e293 - clone
  75:                0x0 - <unknown>


failures:
    services::public::stream_fetch::test::test_stream_fetch_sync

test result: FAILED. 8 passed; 1 failed; 0 ignored; 0 measured; 12 filtered out; finished in 30.19s

error: test failed, to rerun pass '-p fluvio-spu --lib'
make: *** [Makefile:207: run-unstable-test] Error 101
Error: Process completed with exit code 2.
```

_Originally posted by @nicholastmosher in https://github.com/infinyon/fluvio/issues/1264#issuecomment-882542594_

**Comment by sehz** [comment]
Let's try limit number of concurrent threads to stabilize this. https://doc.rust-lang.org/book/ch11-02-running-tests.html

**Comment by nicholastmosher** [comment]
Also, should re rename them? "Unstable" implies they would not block a merge, but this set of tests does do that. Could we rename this something like "fetch tests"?

**Comment by sehz** [comment]
Yeah, "integration tests" or something like that

**Comment by sehz** [comment]
integration test now runs in sequential manner.  hopefully this fixes the issue
