### ISSUE TITLE
Migrate to Rust 2021 edition

### ISSUE THREAD

**Issue by tjtelan** [infinyon/fluvio#1798]
This is a tracking issue to cover the effort around migrating the project to use `edition = 2021`

https://doc.rust-lang.org/edition-guide/editions/transitioning-an-existing-project-to-a-new-edition.html

**Comment by tjtelan** [comment]
First attempt trying to perform this migration failed.

```shell
$ cargo fix --edition
    Checking fluvio-smartstream-derive v0.3.1 (/home/telant/Documents/fluvio/crates/fluvio-smartstream-derive)
    Checking fluvio-protocol-derive v0.3.1 (/home/telant/Documents/fluvio/crates/fluvio-protocol-derive)
   Migrating crates/fluvio-smartstream-derive/src/lib.rs from 2018 edition to 2021
    Checking fluvio-package-index v0.5.0 (/home/telant/Documents/fluvio/crates/fluvio-package-index)
   Migrating crates/fluvio-protocol-derive/src/lib.rs from 2018 edition to 2021
    Checking fluvio-stream-model v0.5.3 (/home/telant/Documents/fluvio/crates/fluvio-stream-model)
    Checking fluvio-protocol v0.6.1 (/home/telant/Documents/fluvio/crates/fluvio-protocol)
    Checking fluvio-types v0.2.6 (/home/telant/Documents/fluvio/crates/fluvio-types)
    Checking fluvio-stream-dispatcher v0.6.5 (/home/telant/Documents/fluvio/crates/fluvio-stream-dispatcher)
   Migrating crates/fluvio-package-index/src/lib.rs from 2018 edition to 2021
   Migrating crates/fluvio-stream-model/src/lib.rs from 2018 edition to 2021
    Checking fluvio-socket v0.10.3 (/home/telant/Documents/fluvio/crates/fluvio-socket)
   Migrating crates/fluvio-protocol/src/lib.rs from 2018 edition to 2021
   Migrating crates/fluvio-types/src/lib.rs from 2018 edition to 2021
   Migrating crates/fluvio-stream-dispatcher/src/lib.rs from 2018 edition to 2021
   Migrating crates/fluvio-protocol/tests/encode.rs from 2018 edition to 2021
   Migrating crates/fluvio-protocol/tests/btreemap.rs from 2018 edition to 2021
   Migrating crates/fluvio-protocol/tests/option.rs from 2018 edition to 2021
   Migrating crates/fluvio-socket/src/lib.rs from 2018 edition to 2021
   Migrating crates/fluvio-protocol/tests/default.rs from 2018 edition to 2021
   Migrating crates/fluvio-protocol-derive/tests/parse.rs from 2018 edition to 2021
   Migrating crates/fluvio-protocol/tests/generic.rs from 2018 edition to 2021
   Migrating crates/fluvio-protocol/tests/enum.rs from 2018 edition to 2021
   Migrating crates/fluvio-protocol/tests/api.rs from 2018 edition to 2021
   Migrating crates/fluvio-protocol/tests/version.rs from 2018 edition to 2021
   Migrating crates/fluvio-protocol/tests/decode.rs from 2018 edition to 2021
error: internal compiler error: compiler/rustc_traits/src/normalize_erasing_regions.rs:54:32: could not fully normalize `<fluvio_stream_model::k8_types::K8Obj<S> as fluvio_stream_model::k8_types::Spec>::Header`

thread 'rustc' panicked at 'Box<dyn Any>', compiler/rustc_errors/src/lib.rs:1147:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.56.0 (09c42c458 2021-10-18) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=1 -C incremental

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [normalize_generic_arg_after_erasing_regions] normalizing `<fluvio_stream_model::k8_types::K8Obj<S> as fluvio_stream_model::k8_types::Spec>::Header`
#1 [adt_significant_drop_tys] computing when `fluvio_stream_model::k8_types::K8List` has a significant destructor
end of query stack
error: could not compile `fluvio-stream-dispatcher`
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by tjtelan** [comment]
Basically the same error message on `beta` (rustc 1.57) toolchain.

However, `cargo +nightly fix --edition` did succeed. So we can at least look forward to having support in a future release.

**Comment by tjtelan** [comment]
This is a more representative output for rustc 1.56.0. (I did a `cargo clean` first)

```shell
   Migrating crates/fluvio-protocol/src/lib.rs from 2018 edition to 2021
    Checking flv-tls-proxy v0.5.0
    Checking fluvio-stream-dispatcher v0.6.5 (/home/telant/Documents/fluvio/crates/fluvio-stream-dispatcher)
   Migrating crates/fluvio-stream-dispatcher/src/lib.rs from 2018 edition to 2021
    Checking fluvio-dataplane-protocol v0.8.0 (/home/telant/Documents/fluvio/crates/fluvio-dataplane-protocol)
   Migrating crates/fluvio-dataplane-protocol/src/lib.rs from 2018 edition to 2021
    Checking fluvio-socket v0.10.3 (/home/telant/Documents/fluvio/crates/fluvio-socket)
   Migrating crates/fluvio-socket/src/lib.rs from 2018 edition to 2021
    Checking zstd v0.9.0+zstd.1.5.0
error: internal compiler error: compiler/rustc_traits/src/normalize_erasing_regions.rs:54:32: could not fully normalize `<fluvio_stream_model::k8_types::K8Obj<S> as fluvio_stream_model::k8_types::Spec>::Header`

thread 'rustc' panicked at 'Box<dyn Any>', compiler/rustc_errors/src/lib.rs:1147:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.56.0 (09c42c458 2021-10-18) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=1 -C incremental --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [normalize_generic_arg_after_erasing_regions] normalizing `<fluvio_stream_model::k8_types::K8Obj<S> as fluvio_stream_model::k8_types::Spec>::Header`
#1 [adt_significant_drop_tys] computing when `fluvio_stream_model::k8_types::K8List` has a significant destructor
end of query stack
error: could not compile `fluvio-stream-dispatcher`
warning: build failed, waiting for other jobs to finish...
thread 'rustc' panicked at 'Box<dyn Any>', compiler/rustc_errors/src/lib.rs:1147:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.56.0 (09c42c458 2021-10-18) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=1 -C incremental

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [normalize_generic_arg_after_erasing_regions] normalizing `<fluvio_stream_model::k8_types::K8Obj<S> as fluvio_stream_model::k8_types::Spec>::Header`
#1 [adt_significant_drop_tys] computing when `fluvio_stream_model::k8_types::K8List` has a significant destructor
end of query stack
error: build failed
```

**Comment by tjtelan** [comment]
As of Rust 1.57, migration works. We'll have to minor version bump all of the published crates (bc we aren't using the major version right now)

**Comment by tjtelan** [comment]
I've run into a little snag with the update. There's a set of proc macro tests that are failing with the same error. Something to do with the `fluvio-smartmodule` re-exports made for the `fluvio-smartmodule-derive` crate not being visible.

Here's one of several similar looking errors from https://github.com/infinyon/fluvio/runs/4451813458?check_suite_focus=true

```
 test derive_ui has been running for over 60 seconds
test ui-tests/pass_agg_with_params.rs ... checking pass
error
┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈
error[E0432]: unresolved imports `fluvio_smartmodule::smartmodule`, `fluvio_smartmodule::SmartOpt`
 --> $DIR/pass_agg_with_params.rs:1:26
  |
1 | use fluvio_smartmodule::{smartmodule, SmartOpt, Result, Record, RecordData};
  |                          ^^^^^^^^^^^  ^^^^^^^^ no `SmartOpt` in the root
  |                          |
  |                          no `smartmodule` in the root

```
