### ISSUE TITLE
smoke test failure in Mac

### ISSUE THREAD

**Issue by sehz** [infinyon/fluvio#589]
```
creating test topic: <topic0>
36
setting rust log: warn
37
>> /Users/runner/work/fluvio/fluvio/./target/release/fluvio topic create topic0 --replication 1
38
topic "topic0" created
39
start testing...
40
found topic: topic0 offset: 0
41
starting fetch stream for: topic0 base offset: 0, expected new records: 1000
42
Dec 21 21:58:21.308 ERROR fluvio_socket::multiplexing: error sending to socket, no socket receiver founded for id: 2, abandoning sending
43
panic panicked at 'start from beginning: PartitionNotFound("topic0", 0)', tests/runner/src/tests/smoke/consume.rs:93:14
44
make: *** [smoke-test-tls-policy] Error 255
45
Error: Process completed with exit code 2.
```

**Comment by sehz** [comment]
Still happening:

```
creating test topic: <topic0>
setting rust log: warn
>> /Users/runner/work/fluvio/fluvio/./target/release/fluvio topic create topic0 --replication 1
topic "topic0" created
start testing...
found topic: topic0 offset: 0

Dec 22 04:50:05.344 ERROR fluvio_socket::multiplexing: error sending to socket, no socket receiver founded for id: 1, abandoning sending
Dec 22 04:50:05.345 ERROR fluvio_socket::multiplexing: error sending to socket, no socket receiver founded for id: 2, abandoning sending
starting fetch stream for: topic0 base offset: 0, expected new records: 1000
panic panicked at 'message sent: PartitionNotFound("topic0", 0)', tests/runner/src/tests/smoke/produce.rs:123:18
make: *** [smoke-test-tls-policy] Error 255
Error: Process completed with exit code 2.

**Comment by sehz** [comment]
Another failure:
```
topic "topic0" created
start testing...
found topic: topic0 offset: 0
starting fetch stream for: topic0 base offset: 0, expected new records: 1000
Dec 22 18:25:18.899 ERROR fluvio_socket::multiplexing: error sending to socket, no socket receiver founded for id: 1, abandoning sending
panic panicked at 'start from beginning: IoError { source: Custom { kind: TimedOut, error: "SPU store lookup failed due to timeout" } }', tests/runner/src/tests/smoke/consume.rs:93:14
make: *** [smoke-test-tls-policy] Error 255
Error: Process completed with exit code 2.
```

**Comment by sehz** [comment]
Failure also happened in the k8-test:

```
NAME: fluvio
LAST DEPLOYED: Mon Dec 28 23:38:19 2020
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
Skipped pre-start checks
Successfully installed Fluvio!
creating test topic: <topic0>
setting rust log: warn
>> /mnt/local_disk/actions/runner/_work/fluvio/fluvio/target/x86_64-unknown-linux-musl/release/fluvio topic create topic0 --replication 1
topic "topic0" created
start testing...
found topic: topic0 offset: 0
starting fetch stream for: topic0 base offset: 0, expected new records: 1000
Dec 28 23:38:34.707 ERROR fluvio_socket::multiplexing: error sending to socket, no socket receiver founded for id: 2, abandoning sending
panic panicked at 'message sent: PartitionNotFound("topic0", 0)', tests/runner/src/tests/smoke/produce.rs:123:18
make: *** [smoke-test-k8-tls-policy] Error 255
Makefile:84: recipe for target 'smoke-test-k8-tls-policy' failed
Error: Process completed with exit code 2.
```

**Comment by sehz** [comment]
successful trace looks like this:
```

201
Dec 30 01:59:14.111 DEBUG dispatch_loop{spec="Partition"}: fluvio::sync::controller: processing Partition, sync all items: 1
202
Dec 30 01:59:14.111 DEBUG dispatch_loop{spec="SPU"}: fluvio::sync::controller: processing SPU, sync all items: 1
203
Dec 30 01:59:14.111 DEBUG dispatch_loop{spec="Partition"}: fluvio_stream_model::store::dual_store: SyncAll: <Partition> epoch: 0 incoming 1
204
Dec 30 01:59:14.111 DEBUG dispatch_loop{spec="SPU"}: fluvio_stream_model::store::dual_store: SyncAll: <SPU> epoch: 0 incoming 1
205
Dec 30 01:59:14.111 DEBUG dispatch_loop{spec="Partition"}: fluvio_stream_model::store::dual_store: Sync all: <Partition:1> [add:1, mod_spec:0, mod_status: 0, mod_meta: 0, del:0], 
206
Dec 30 01:59:14.111 DEBUG dispatch_loop{spec="SPU"}: fluvio_stream_model::store::dual_store: Sync all: <SPU:1> [add:1, mod_spec:0, mod_status: 0, mod_meta: 0, del:0], 
207
Dec 30 01:59:14.111 DEBUG send_record{partition=0 topic="topic0"}: fluvio::sync::context: checking to see if exists SPEC="Partition"
208
Dec 30 01:59:14.111 DEBUG send_record{partition=0 topic="topic0"}: fluvio::sync::context: found value SPEC="Partition"
209
Dec 30 01:59:14.111 DEBUG send_record{partition=0 topic="topic0"}: fluvio::sync::context: checking to see if exists SPEC="SPU"
210
Dec 30 01:59:14.111 DEBUG send_record{partition=0 topic="topic0"}: fluvio::sync::context: found value SPEC="SPU"
211
Dec 30 01:59:14.111 DEBUG send_record{partition=0 topic="topic0"}: fluvio::spu::spu_pool: connecting to spu: id: 5001, type: "custom", public: localhost:9010
212
Dec 30 01:59:14.111 DEBUG send_record{partition=0 topic="topic0"}: fluvio::spu::spu_pool: spu addr: localhost:9010
213
Dec 30 01:59:14.111 DEBUG send_record{partition=0 topic="topic0"}: fluvio_socket::socket: trying to connect to addr at: localhost:9010
214
Dec 30 01:59:14.111 DEBUG send_record{partition=0 topic="topic0"}: fluvio_future::native_tls::connector: connect to tls addr: localhost:9010    
215
Dec 30 01:59:14.112 DEBUG send_record{partition=0 topic="topic0"}: fluvio_future::native_tls::connector: connect to tls domain: fluvio.local    
216
Dec 30 01:59:14.123 DEBUG send_record{partition=0 topic="topic0"}: fluvio_socket::multiplexing: dispatcher: spawning dispatcher loop
217
Dec 30 01:59:14.123 DEBUG send_record{partition=0 topic="topic0"}: fluvio::producer: connect to replica leader at: config addr localhost:9010
218
Dec 30 01:59:14.123 DEBUG send_record{partition=0 topic="topic0"}: fluvio::producer: send record 112 bytes to: replica: topic0-0, config addr localhost:9010
219
Dec 30 01:59:14.123 DEBUG send_record{partition=0 topic="topic0"}: fluvio_socket::multiplexing: serial multiplexing: sending request: 0 id: 1
220
Dec 30 01:59:14.123 DEBUG fluvio_socket::multiplexing: dispatcher: waiting for next response from stream 
221
Dec 30 01:59:14.124 DEBUG fluvio_socket::multiplexing: dispatcher: decoded correlation id: 1
222
Dec 30 01:59:14.124 DEBUG fluvio_socket::multiplexing: dispatcher: waiting for next response from stream 
223
Dec 30 01:59:14.124 DEBUG send_record{partition=0 topic="topic0"}: fluvio_socket::multiplexing: receive serial socket id: 1, bytes: 50
224
Dec 30 01:59:14.125 DEBUG fluvio_socket::multiplexing: dispatcher: decoded correlation id: 1
225
Dec 30 01:59:14.125 DEBUG fluvio_socket::multiplexing: dispatcher: waiting for next response from stream 
226
Dec 30 01:59:14.142 DEBUG send_record{partition=0 topic="topic0"}: fluvio::producer: sending records: 112 bytes to: topic0-0
227
Dec 30 01:59:14.142 DEBUG send_record{partition=0 topic="topic0"}: fluvio::sync::context: lookup for Partition key: topic0-0
228
Dec 30 01:59:14.142 DEBUG send_record{partition=0 topic="topic0"}: fluvio::sync::context: checking to see if exists SPEC="Partition"
229
Dec 30 01:59:14.142 DEBUG send_record{partition=0 topic="topic0"}: fluvio::sync::context: found value SPEC="Partition"
230
Dec 30 01:59:14.142 DEBUG send_record{partition=0 topic="topic0"}: fluvio::producer: connect to replica leader at: config addr localhost:9010
231
Dec 30 01:59:14.142 DEBUG send_record{partition=0 topic="topic0"}: fluvio::producer: send record 112 bytes to: replica: topic0-0, config addr localhost:9010
232
Dec 30 01:59:14.142 DEBUG send_record{partition=0 topic="topic0"}: fluvio_socket::multiplexing: serial multiplexing: sending request: 0 id: 2
233
Dec 30 01:59:14.142 DEBUG fluvio_socket::multiplexing: dispatcher: decoded correlation id: 2
234
Dec 30 01:59:14.143 DEBUG fluvio_socket::multiplexing: dispatcher: waiting for next response from stream 
235
Dec 30 01:59:14.143 DEBUG send_record{partition=0 topic="topic0"}: fluvio_socket::multiplexing: receive serial socket id: 2, bytes: 50
236
Dec 30 01:59:14.143 DEBUG fluvio_socket::multiplexing: dispatcher: decoded correlation id: 1
237
Dec 30 01:59:14.143 DEBUG fluvio_socket::multiplexing: dispatcher: waiting for next response from stream 
238
Dec 30 01:59:14.159 DEBUG send_record{partition=0 topic="topic0"}: fluvio::producer: sending records: 112 bytes to: topic0-0
239
Dec 30 01:59:14.160 DEBUG send_record{partition=0 topic="topic0"}: fluvio::sync::context: lookup for Partition key: topic0-0
240
Dec 30 01:59:14.160 DEBUG send_record{partition=0 topic="topic0"}: fluvio::sync::context: checking to see if exists SPEC="Partition"
241
Dec 30 01:59:14.160 DEBUG send_record{partition=0 topic="topic0"}: fluvio::sync::context: found value SPEC="Partition"
242
Dec 30 01:59:14.160 DEBUG send_record{partition=0 topic="topic0"}: fluvio::producer: connect to replica leader at: config addr localhost:9010
243
Dec 30 01:59:14.160 DEBUG send_record{partition=0 topic="topic0"}: fluvio::producer: send record 112 bytes to: replica: topic0-0, config addr localhost:9010
244
Dec 30 01:59:14.160 DEBUG send_record{partition=0 topic="topic0"}: fluvio_socket::multiplexing: serial multiplexing: sending request: 0 id: 3
245
Dec 30 01:59:14.160 DEBUG fluvio_socket::multiplexing: dispatcher: decoded correlation id: 3
246
Dec 30 01:59:14.160 DEBUG fluvio_socket::multiplexing: dispatcher: waiting for next response from stream 
247
Dec 30 01:59:14.160 DEBUG send_record{partition=0 topic="topic0"}: fluvio_socket::multiplexing: receive serial socket id: 3, bytes: 50
248
Dec 30 01:59:14.161 DEBUG fluvio_socket::multiplexing: dispatcher: decoded correlation id: 1
249
Dec 30 01:59:14.161 DEBUG fluvio_socket::multiplexing: dispatcher: waiting for next response from stream 
250
Dec 30 01:59:14.174 DEBUG send_record{partition=0 topic="topic0"}: fluvio::producer: sending records: 112 bytes to: topic0-0
```
