### ISSUE TITLE
CI Failure: test_replication2_new_records_sync

### ISSUE THREAD

**Issue by nicholastmosher** [infinyon/fluvio#982]
I just had this unit test fail in CI. Here is the link to the action output but it will probably get overwritten: https://github.com/infinyon/fluvio/pull/965/checks?check_run_id=2394858608

```
$ make build-all-test run-all-unit-test
...

     Running target/debug/deps/fluvio_spu-9d55d6824d2e1e36

running 19 tests
test core::spus::metadata::test::test_indexed_by_id ... ok
test core::store::test::test_apply_changes ... ok
test core::store::test::test_sync_all ... ok
test core::spus::metadata::test::test_peer_spu_routines ... ok
test replication::follower::state::follower_tests::test_follower_creation_sync ... ok
test replication::leader::replica_state::test_hw_updates::test_hw22 ... ok
test replication::leader::replica_state::test_hw_updates::test_hw32 ... ok
test replication::leader::replica_state::test_hw_updates::test_hw33 ... ok
test replication::leader::leaders_state::test_channel::test_event_shutdown_sync ... ok
test replication::leader::replica_state::test_hw_updates::test_hw_min_lsr_invalid_hw ... ok
test replication::leader::replica_state::test_hw_updates::test_hw_min_lsr_too_much ... ok
test replication::leader::replica_state::test_leader::test_update_leader_from_followers_sync ... ok
test replication::leader::replica_state::test_leader::test_follower_update_sync ... ok
test replication::replica_test::test_initial_replication_sync ... ok
test replication::replica_test::test_replication2_new_records_sync ... FAILED
test services::public::stream_fetch::test::test_stream_fetch_sync ... ok
test services::public::stream_fetch::test::test_stream_filter_fetch_sync ... ok
test smart_stream::filter::test::test_file ... ok
test services::public::stream_fetch::test::test_stream_filter_max_sync ... ok

failures:

---- replication::replica_test::test_replication2_new_records_sync stdout ----
thread 'replication::replica_test::test_replication2_new_records_sync' panicked at 'assertion failed: `(left == right)`
  left: `0`,
 right: `2`', src/spu/src/replication/mod.rs:216:9
stack backtrace:
   0:     0x55731386cda0 - std::backtrace_rs::backtrace::libunwind::trace::h5e9d00f0cdf4f57e
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x55731386cda0 - std::backtrace_rs::backtrace::trace_unsynchronized::hd5302bd66215dab9
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55731386cda0 - std::sys_common::backtrace::_print_fmt::ha0237cd11a34e2bf
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x55731386cda0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h171d4c10df1a98ee
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x55731389083c - core::fmt::write::h89e4288724daa3fa
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/fmt/mod.rs:1096:17
   5:     0x557313864b12 - std::io::Write::write_fmt::h61989113371c2355
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/io/mod.rs:1568:15
   6:     0x55731386f455 - std::sys_common::backtrace::_print::h0c0b93221682afc8
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x55731386f455 - std::sys_common::backtrace::print::h57a9f95204c2fdd6
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x55731386f455 - std::panicking::default_hook::{{closure}}::h4245258b50e37e69
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:208:50
   9:     0x55731386efeb - std::panicking::default_hook::h7b00dcc1d0944747
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:222:9
  10:     0x55731386fbf1 - std::panicking::rust_panic_with_hook::h71e6a073d87de1f5
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:591:17
  11:     0x55731386f737 - std::panicking::begin_panic_handler::{{closure}}::hd549436f6bb6dbb8
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:497:13
  12:     0x55731386d23c - std::sys_common::backtrace::__rust_end_short_backtrace::h4e5f4b72b04174c3
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x55731386f699 - rust_begin_unwind
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:493:5
  14:     0x55731388e981 - core::panicking::panic_fmt::hcd56f7f635f62c74
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/panicking.rs:92:14
  15:     0x557312519cca - fluvio_spu::replication::replica_test::test_replication2_new_records_sync::test_replication2_new_records::{{closure}}::hfe578ea5fc2816c0
                               at /home/runner/work/fluvio/fluvio/src/spu/src/replication/mod.rs:216:9
  16:     0x557312618639 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h62868e8ae9a8ff84
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/future/mod.rs:80:19
  17:     0x557312517d1c - fluvio_spu::replication::replica_test::test_replication2_new_records_sync::{{closure}}::h32bf31c3cc69e8f0
                               at /home/runner/work/fluvio/fluvio/src/spu/src/replication/mod.rs:135:5
  18:     0x55731261e029 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hd6041ae706709a32
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/future/mod.rs:80:19
  19:     0x5573124dfe39 - <async_std::task::builder::SupportTaskLocals<F> as core::future::future::Future>::poll::{{closure}}::haf4e65d1c3fe74d3
                               at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.9.0/src/task/builder.rs:199:17
  20:     0x55731258f0f3 - async_std::task::task_locals_wrapper::TaskLocalsWrapper::set_current::{{closure}}::h81f3fed873675a54
                               at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.9.0/src/task/task_locals_wrapper.rs:60:13
  21:     0x5573127231e5 - std::thread::local::LocalKey<T>::try_with::hfddb0f5f91cc5fcc
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/thread/local.rs:272:16
  22:     0x55731271a85d - std::thread::local::LocalKey<T>::with::ha524a7bbb2bea820
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/thread/local.rs:248:9
  23:     0x55731258de6b - async_std::task::task_locals_wrapper::TaskLocalsWrapper::set_current::h813c7a4d4b0cc682
                               at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.9.0/src/task/task_locals_wrapper.rs:55:9
  24:     0x5573124df468 - <async_std::task::builder::SupportTaskLocals<F> as core::future::future::Future>::poll::h12a0d4f74fb8c3e6
                               at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.9.0/src/task/builder.rs:197:13
  25:     0x5573127aa09a - <futures_lite::future::Or<F1,F2> as core::future::future::Future>::poll::hd42bdc3bc2376b2a
                               at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-lite-1.11.3/src/future.rs:526:33
  26:     0x5573125950fa - async_executor::Executor::run::{{closure}}::hf17704906e044ebb
                               at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/async-executor-1.4.0/src/lib.rs:236:9
  27:     0x557312616209 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h29392e0b9b664a11
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/future/mod.rs:80:19
  28:     0x557312591d02 - async_executor::LocalExecutor::run::{{closure}}::h83c380ddc341b42a
                               at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/async-executor-1.4.0/src/lib.rs:437:9
  29:     0x557312614b19 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h0774bb9d90353edd
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/future/mod.rs:80:19
  30:     0x55731276a8a2 - async_io::driver::block_on::h8e6ba31bd439d94a
                               at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/async-io-1.4.0/src/driver.rs:142:33
  31:     0x557312621e8b - async_global_executor::reactor::block_on::{{closure}}::he8f84a5d2ec7d285
                               at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/async-global-executor-2.0.2/src/reactor.rs:3:18
  32:     0x557312621ad8 - async_global_executor::reactor::block_on::h8a2c3d52844568ae
                               at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/async-global-executor-2.0.2/src/reactor.rs:12:5
  33:     0x5573127d79c2 - async_global_executor::executor::block_on::{{closure}}::h655d2be71da77f21
                               at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/async-global-executor-2.0.2/src/executor.rs:26:36
  34:     0x55731271fcde - std::thread::local::LocalKey<T>::try_with::h9381ee936d87d1de
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/thread/local.rs:272:16
  35:     0x55731271a98d - std::thread::local::LocalKey<T>::with::hae262ced586a7640
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/thread/local.rs:248:9
  36:     0x5573127d7566 - async_global_executor::executor::block_on::h7315490995e68058
                               at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/async-global-executor-2.0.2/src/executor.rs:26:5
  37:     0x5573124e85d6 - async_std::task::builder::Builder::blocking::{{closure}}::{{closure}}::h65be1c54f7d2daed
                               at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.9.0/src/task/builder.rs:171:25
  38:     0x55731258eeee - async_std::task::task_locals_wrapper::TaskLocalsWrapper::set_current::{{closure}}::h71cb24e862dc5ad4
                               at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.9.0/src/task/task_locals_wrapper.rs:60:13
  39:     0x55731271f8de - std::thread::local::LocalKey<T>::try_with::h900fbc3b9d014fc4
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/thread/local.rs:272:16
  40:     0x55731271a4bd - std::thread::local::LocalKey<T>::with::h90f47d584dacfc6c
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/thread/local.rs:248:9
  41:     0x55731258e282 - async_std::task::task_locals_wrapper::TaskLocalsWrapper::set_current::hea6e45d37af36039
                               at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.9.0/src/task/task_locals_wrapper.rs:55:9
  42:     0x5573124e7705 - async_std::task::builder::Builder::blocking::{{closure}}::h104889ce29ba43f8
                               at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.9.0/src/task/builder.rs:168:17
  43:     0x55731272007e - std::thread::local::LocalKey<T>::try_with::h96eb537ce52e56db
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/thread/local.rs:272:16
  44:     0x55731271ac0d - std::thread::local::LocalKey<T>::with::hb725be9841b9c23f
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/thread/local.rs:248:9
  45:     0x5573124e6168 - async_std::task::builder::Builder::blocking::h6a7eb4f8339e5113
                               at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.9.0/src/task/builder.rs:161:9
  46:     0x5573125bde77 - async_std::task::block_on::block_on::h63fdc3e571836629
                               at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.9.0/src/task/block_on.rs:33:5
  47:     0x55731253ab35 - fluvio_future::task::run_block_on::h67bb4b465799e129
                               at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/fluvio-future-0.2.0/src/task.rs:61:5
  48:     0x5573127c9b7c - fluvio_spu::replication::replica_test::test_replication2_new_records_sync::h1daa1ceaf1c70004
                               at /home/runner/work/fluvio/fluvio/src/spu/src/replication/mod.rs:135:5
  49:     0x557312517c4a - fluvio_spu::replication::replica_test::test_replication2_new_records_sync::{{closure}}::h4a902eec4d798f92
                               at /home/runner/work/fluvio/fluvio/src/spu/src/replication/mod.rs:135:5
  50:     0x5573125d96de - core::ops::function::FnOnce::call_once::h1a6e27121353999e
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/ops/function.rs:227:5
  51:     0x557313349cb3 - core::ops::function::FnOnce::call_once::h39334accff073405
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/ops/function.rs:227:5
  52:     0x557313349cb3 - test::__rust_begin_short_backtrace::h67066ecbe74d57fb
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/test/src/lib.rs:557:5
  53:     0x557313348371 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h1a2fa75e4663d5fb
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/alloc/src/boxed.rs:1521:9
  54:     0x557313348371 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h51ed23ef8108a70b
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panic.rs:344:9
  55:     0x557313348371 - std::panicking::try::do_call::ha481e088fadbcefb
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:379:40
  56:     0x557313348371 - std::panicking::try::h79dbf3ffc900b110
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:343:19
  57:     0x557313348371 - std::panic::catch_unwind::hd5e087ec559ee8c6
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panic.rs:431:14
  58:     0x557313348371 - test::run_test_in_process::h84f8f1a053afd5c9
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/test/src/lib.rs:579:18
  59:     0x557313348371 - test::run_test::run_test_inner::{{closure}}::h5ab37355828267a7
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/test/src/lib.rs:487:39
  60:     0x55731331fcd6 - std::sys_common::backtrace::__rust_begin_short_backtrace::hdbdda9b291bb4f07
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:125:18
  61:     0x55731332446d - std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}::hc46a4b3ec40c9eed
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/thread/mod.rs:474:17
  62:     0x55731332446d - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h05957c6c69ac6289
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panic.rs:344:9
  63:     0x55731332446d - std::panicking::try::do_call::h8bc73718b8794c20
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:379:40
  64:     0x55731332446d - std::panicking::try::h5b8d8bd1a29e08ec
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:343:19
  65:     0x55731332446d - std::panic::catch_unwind::hc7d07542f03f4fe0
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panic.rs:431:14
  66:     0x55731332446d - std::thread::Builder::spawn_unchecked::{{closure}}::hc18fb3dc9d95423d
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/thread/mod.rs:473:30
  67:     0x55731332446d - core::ops::function::FnOnce::call_once{{vtable.shim}}::h41e1c7de77e3395e
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/ops/function.rs:227:5
  68:     0x557313877afa - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h61144a2be4ee36d8
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/alloc/src/boxed.rs:1521:9
  69:     0x557313877afa - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hcf5d395fdd120c17
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/alloc/src/boxed.rs:1521:9
  70:     0x557313877afa - std::sys::unix::thread::Thread::new::thread_start::hb5e40d3d934ebb7a
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys/unix/thread.rs:71:17
  71:     0x7fb22e75d609 - start_thread
  72:     0x7fb22e52d293 - clone
  73:                0x0 - <unknown>


failures:
    replication::replica_test::test_replication2_new_records_sync

test result: FAILED. 18 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 7.83s

error: test failed, to rerun pass '-p fluvio-spu --lib'
make: *** [Makefile:170: run-all-unit-test] Error 101
```

**Comment by sehz** [comment]
should be fixed #987
